[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "PyLiquid2EVM"
version = "1.0.0"
description = "Python Module to Interact with Liquid Blockchain"
readme = "README.md"